### ISSUE TITLE
i3 template errors

### ISSUE THREAD

**Issue by xHN35RQ** [xHN35RQ/base16-builder#1]
From @pickfire: 

I have tested `i3` and `i3status`, it seems that `i3` is a bit weird and it have weird status color.

`i3status` seems to have the wrong **good color** as it uses *yellow* instead of *green*.

![2015-08-20-165651_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/9379516/7e75a9d2-475c-11e5-857a-7bc8137d43a7.png)

I does not seem to know how to use `i3-style`.

I have also created an issue in the original base16 repo, I think I will try to file a pull request to improve the `mutt` theme if there is anything missing. Look at https://github.com/chriskempson/base16-builder/issues/247#issuecomment-120827936.

**Comment by xHN35RQ** [comment]
Are you using `dmenu` as well?

These templates were authored by @parnmatt https://github.com/parnmatt/base16-builder/commit/e66454c008f90604340742fd367495e73e92f43d

And additional changes were made by @rti https://github.com/rti/base16-builder/commits/rti

I just merged their commits into my branch.

**Comment by pickfire** [comment]
> Are you using dmenu as well?

Yes.

Maybe I experience the errors because I does not use `i3-style`.

**Comment by parnmatt** [comment]
@pickfire I only didn't use i3-style myself

This is in my dotfiles, copied verbatim from what's on github, (however including the filename):
```
# $HOME/.i3status.conf
general {
    colors = true
    color_good = "#b5bd68"  # base0B
    color_bad = "#cc6666"  # base08
    interval = 5
}
```

**Comment by pickfire** [comment]
Well, your one does look nice if it is without the `i3status` config as the font are too hard to read. But the patch I used is worse.

![2015-08-22-215720_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/9424266/eb7f8a8a-4918-11e5-9fea-5198240314e1.png)

**Comment by parnmatt** [comment]
The above config I posted gives this, I think it's fine. The tomorrow scheme was supposed to be a little pastely, however it's still clearly readable here.

![2015-08-22-153419_1920x1080_scrot](https://cloud.githubusercontent.com/assets/318829/9424406/47de07c4-48e3-11e5-94a6-af505eb74f10.png)

If you dislike the colour that is used, then change it :) I chose to keep thue to the theme and use the green and red hexvalues, however there's nothing stopping you from changing it to a different green/red/any colour.

**Comment by pickfire** [comment]
It still seems like yours is different from mine for the i3status.

**Comment by parnmatt** [comment]
Can you link or post your whole i3 config?

**Comment by xHN35RQ** [comment]
@parnmatt  thanks for stepping in to assist :smile:

**Comment by parnmatt** [comment]
@pickfire Indeed it is, fell in love with it when I found it, however I cannot think where I got it from, a reverse image search gives me this: http://wallpaperswide.com/red_forest_4-wallpapers.html

@xHN35RQ no problem, I'm one who believes if you write it, you maintain it. So I'll do my best to debug :)

**Comment by pickfire** [comment]
My current configuration:
https://github.com/pickfire/dotfiles/blob/master/home/config/i3/config

Do you need the one after the patch?

**Comment by parnmatt** [comment]
@pickfire, It may help; I will have a look at this and the patched version to see if I can see a reason for the mess up.

**Comment by pickfire** [comment]
`i3`:

```conf
...
# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"
# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode
        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym h resize shrink width 10 px or 10 ppt
        bindsym j resize grow height 10 px or 10 ppt
        bindsym k resize shrink height 10 px or 10 ppt
        bindsym l resize grow width 10 px or 10 ppt
        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt
        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}
bindsym $mod+r mode "resize"
# ~/.i3/config
# i3 config template
# Base16 Solarized by Ethan Schoonover (http://ethanschoonover.com/solarized)
# template by Matt Parnell, @parnmatt
set $base00 #002b36
set $base01 #073642
set $base02 #586e75
set $base03 #657b83
set $base04 #839496
set $base05 #93a1a1
set $base06 #eee8d5
set $base07 #fdf6e3
set $base08 #dc322f
set $base09 #cb4b16
set $base0A #b58900
set $base0B #859900
set $base0C #2aa198
set $base0D #268bd2
set $base0E #6c71c4
set $base0F #d33682
client.focused $base0D $base0D $base00 $base0D
client.focused_inactive $base02 $base02 $base03 $base02
client.unfocused $base01 $base01 $base03 $base01
client.urgent $base02 $base08 $base07 $base02

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        position        bottom
        status_command  i3status
        colors {
                separator $base03
                background $base01
                statusline $base05
                focused_workspace $base0C $base0D $base00
                active_workspace $base02 $base02 $base07
                inactive_workspace $base01 $base01 $base03
                urgent_workspace $base08 $base08 $base07
        }
}
```

In `i3status`, line `    color_bad = "dc322f"` seems to be missing `#` and there is an error. After adding `#`, it sems to work fine.

```conf
# ~/.i3status.conf
# Base16 Solarized, by Ethan Schoonover (http://ethanschoonover.com/solarized)
# template by Matt Parnell, @parnmatt

general {
    colors = true
    color_good = "#859900"
    color_bad = "#dc322f"
    ## remember to add your prefered interval
    interval = 5
}

## remember to add the rest of your configure
order += "volume master"
```

**Comment by xHN35RQ** [comment]
@pickfire @parnmatt Any progress on this? Just curious if this issue needs to remain open. Thanks!

**Comment by pickfire** [comment]
@xHN35RQ There isn't any improvement currently, I think we will see what @parnmart say.

**Comment by xHN35RQ** [comment]
Ok we'll keep it open for a bit.

**Comment by parnmatt** [comment]
Sorry the last couple of weeks have been busy.

I didn't remember seeing anything wrong before. I just had a look now, and still nothing.
I've changed my own config to use solarized style and it looks ok. I then made the couple of changes you have done in the above config, almost no visual change except red --> grey for urgent.

In one of the screenshots you've got a purple (active?) window, which would be $base0E, however not 0E is in the config given.

I'm going to have to say I have no clue what your issue is. The colours look fine to me. Sorry.

**Comment by pickfire** [comment]
I will test it and give a reply.

**Comment by pickfire** [comment]
The i3bar is still green and I still can't figured out the problem. May I ask what version of i3 are you using?

I am using `i3 version 4.10.4 (2015-09-08, branch "4.10.4") © 2009-2014 Michael Stapelberg and contributors`

There is a v4 config.

**Comment by pickfire** [comment]
It seems like there is a new config which is [`client.placeholder`](http://i3wm.org/docs/userguide.html#_changing_colors).

I figured it out, it seems like it is a bug. https://github.com/i3/i3/issues/434

**Comment by parnmatt** [comment]
@pickfire I'm using the same version `i3 version 4.10.4 (2015-09-08, branch "4.10.4") © 2009-2014 Michael Stapelberg and contributors`.

Oh I'm partially glad this is an issue with i3 rather than this project. However it's an old issue, surprised it's still affecting people.

I believe this particular issue can be closed, there's nothing we can do here.

**Comment by xHN35RQ** [comment]
Ok thanks for the update.
