### ISSUE TITLE
add newsbeuter template

### ISSUE THREAD

**Issue by xHN35RQ** [xHN35RQ/base16-builder#2]
see https://github.com/xHN35RQ/base16-builder/issues/2#issuecomment-142901445

**Comment by pickfire** [comment]
[The one I provided](https://github.com/chriskempson/base16-builder/issues/284#issue-94651002) is the one I am using currently, maybe you could just add **info** about the location of the file which is `~/.newsbeuter/config`.

**Comment by xHN35RQ** [comment]
Well, that's a finished theme, we need to work on the ruby template for base16-builder that will be able to build all the different color themes.

**Comment by pickfire** [comment]
![2015-08-23-171951_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/9427650/3750ae24-49bb-11e5-8a21-eb015e32bea4.png)
![2015-08-23-171956_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/9427651/377d11c6-49bb-11e5-8ebd-c83688ce454c.png)
![2015-08-23-171959_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/9427652/37abcdea-49bb-11e5-93b9-13e115b2d234.png)

I still haven't found of a way to improve the coloring in the third example.

**Comment by xHN35RQ** [comment]
I have a similar styling, I use more basic styling. Now that I think about it, I don't know if newsbeuter needs an official template, since it picks up the colors from the terminal so it's largely dependent on whichever base16-shell theme you're using.

**Comment by pickfire** [comment]
Yeah, so I think we should at least give them to steal some basic color for styling, I took some time in configuring that too. It seems that I cannot get a light theme to work on it.

**Comment by xHN35RQ** [comment]
I don't have time to make a newsbeuter ruby template at the moment. And it's easy enough to set the colors in the newsbeuter config; a theme template would be nice, but unless you have a ruby template to merge in I'm going to close this issue.

**Comment by pickfire** [comment]
Then, I think I am going to make one althought it is easy, but I think if a template can solved anything, I don't think we need to generate it twice.

Maybe we could just generate a flexible template once for some templates such as mutt.

**Comment by xHN35RQ** [comment]
Proper newsbeuter theme support requires 256 color support from https://github.com/chriskempson/base16-builder/pull/296

**Comment by xHN35RQ** [comment]
Added a basic newsbeuter template https://github.com/xHN35RQ/base16-builder/commit/7b883e6945874641370b3b5359c336af32d5d17f

**Comment by pickfire** [comment]
It seems like I still have no way to get a light background work.

**Comment by xHN35RQ** [comment]
The newsbeuter template I just added is dark background for the moment, it's still a work in progress. I think you'll need to have a light shell template AND a light newsbeuter working at the same time in order for newesbeuter to have a light background.

**Comment by pickfire** [comment]
I think I had tried that before but not working for newsbeuter but working for mutt.

**Comment by xHN35RQ** [comment]
Ah ok. I'm going to work on newsbeuter theme some more in future, and I mean to create light and dark versions, so I'll figure it out then.

**Comment by pickfire** [comment]
I had already created a dark version. There is also some bug for newsbeuter which the newer version can't highlight multiple items. https://github.com/akrennmair/newsbeuter/issues/166

**Comment by pickfire** [comment]
When I use the light shell template for `st` terminal, it doesn't have a light background.

**Comment by pickfire** [comment]
Note that I use `base19` instead of `base18` in dark colorscheme **info** *foreground* because it have some bug. https://github.com/akrennmair/newsbeuter/issues/186

I just did the light colorscheme:
```
color background              color19 color15
color listnormal              color19 color15
color listfocus               color21 color03
color info                    color20 color21
color article                 color19 color15
color listfocus_unread        color21 color03 bold

highlight article "^Title:.*" color04 color15
highlight article "^Feed:.*"  color03 color15
```

**Comment by pickfire** [comment]
I just hope that you could add some info about conversion from dark theme to light theme to enable others to convert colorschemes easily.

**Comment by xHN35RQ** [comment]
I will make both a basic dark and light version of the template at some point in future, but right now base16 does not have support for `color00` color formats, which is something I hope to fix. Once we have support for 256 color formats we can easily use the dark and light templates to generate newsbeuter color configurations for every different base16 theme.

**Comment by pickfire** [comment]
It think it is solved now.

**Comment by xHN35RQ** [comment]
> It think it is solved now.

What is solved, and how?

**Comment by pickfire** [comment]
I have created both light and dark themes.

**Comment by xHN35RQ** [comment]
Where?

**Comment by pickfire** [comment]
I had posted it as comment. Look at:
https://github.com/xHN35RQ/base16-builder/issues/2#issuecomment-143139417
https://github.com/chriskempson/base16-builder/issues/284#issue-94651002

**Comment by xHN35RQ** [comment]
Ah ok, thanks. I'll look at those.

**Comment by xHN35RQ** [comment]
closing since i've decided not to work on this.
