### ISSUE TITLE
Improve mutt template

### ISSUE THREAD

**Issue by xHN35RQ** [xHN35RQ/base16-builder#3]
Only improve if there are major errors.

**Comment by pickfire** [comment]
![2015-08-22-214225_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/9424217/bbc82484-4916-11e5-9406-f20e5f3ac63e.png)

Which one do you like more? Left is mine (which I took some pieces from solarized) and the right is the base16-builder patch.

If you have any question or something you would like to improve on, I hope you can point them out.

**Comment by xHN35RQ** [comment]
I don't use mutt, so I'm not planning on improving the mutt theme unless there are errors that you can bring forward. Do you see anything that's a major problem when using this theme?

**Comment by pickfire** [comment]
Sorry I give you the wrong image:

![2015-08-23-171626_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/9427636/be884d76-49ba-11e5-85d5-f5236c7aefa4.png)

> Which one do you like more? Left is mine (which I took some pieces from solarized) and the right is the base16-builder patch.

Still the same.

**Comment by xHN35RQ** [comment]
It's subjective. I like the one on the right. Too much red on the left. But the core question is: do you see any errors or problems with the existing template?

**Comment by pickfire** [comment]
> But the core question is: do you see any errors or problems with the existing template?

No.

> Too much red on the left.

I use red for links because I need to differentiated it between the rest. Some improvement for the right:

1. Add hightlight for `Date:`, `From:`, `To:`... (using background color is ugly)
2. Show that the message is old (not viewed) or new (not viewed)
3. Differentiate between a link and non-link (use a non-red, maybe yellow)
4. Use a better color to select messages (don't use grey, hard to differentiate)

What do you think I should improved?

**Comment by xHN35RQ** [comment]
> What do you think I should improved?

I really don't know. I don't use mutt so I can't give an informed opinion. Sorry.

**Comment by pickfire** [comment]
Can I create some pul request?

**Comment by xHN35RQ** [comment]
Sure!

**Comment by xHN35RQ** [comment]
I added your templates to `templates/mutt` but renamed them to `alt` in 30feb91a4ca6f5c5f4461dda878fd1adcc103eb1

**Comment by pickfire** [comment]
Some mutt update patch:
```
--- output/mutt/base16-solarized.dark.alt.256.muttrc    2015-09-25 10:34:55.002121002 +0800
+++ /home/ivan/.mutt/base16-solarized   2015-09-21 22:57:47.042224829 +0800
@@ -87,7 +86,6 @@ color tree        color03     color00

 # Index
 color index       color20     color00     "~A"       # all messages
-color index       color06     color00     "~O"       # message is old
 color index       color07     color00     "~F"       # flagged messages
 color index       color03     color00     "~P"       # message is PGP encrypted
 color index       color02     color00     "~S"       # message is signed and signature is verified
@@ -95,13 +93,14 @@ color index       color20     color00
 color index       color04     color00     "~U"       # unread messages
 color index       color04     color00     "~v~(~N)"  # collapsed thread with some unread
 color index       color02     color00     "~v~(~F)"  # collapsed thread with some flagged
+color index       color06     color00     "~O"       # message is old
 color index       color18     color02     "~T"       # tagged message
 color index       color18     color01     "~D"       # message mark for deletion

 # Header
-color hdrdefault  color19     color18
-color header      color08     color18     "^(From)"
-color header      color06     color18     "^(Subject)"
+color hdrdefault  color19     color00
+color header      color08     color00     "^(From)"
+color header      color06     color00     "^(Subject)"
 color header      color01     color00     "^(X-spam-rule)"
 color header      color01     color00     "^(X-SpamProbe: SPAM)"

```

**Comment by xHN35RQ** [comment]
Can you please submit a pull request for any updates? Thanks.
